name: HitAndBlow
main: com.github.ucchyocean.hitandblow.HitAndBlowPlugin
version: 1.1.0
authors: [ucchy]
load: startup
description: Minecraft Hit And Blow Game.
commands:
  hitandblow:
    description: Minecraft Hit And Blow Game.
    aliases: hb
    usage: /<command> - Minecraft Hit And Blow Game Command.
    permission: hitandblow
    permission-message: You don't have permission <permission>
permissions:
  hitandblow:
    description: Minecraft Hit And Blow Game command.
