name: HitAndBlow
main: org.github.ucchyocean.hitandblow.HitAndBlowPlugin
version: 1.0.1
authors: [ucchy]
load: startup
description: Minecraft Hit And Blow Game.
commands:
  hb:
    description: Minecraft Hit And Blow Game.
    usage: |
           /<command> - Minecraft Hit And Blow Game Command.
    permission: hitandblow
    permission-message: You don't have permission <permission>
permissions:
  hitandblow:
    description: Minecraft Hit And Blow Game command.
